selezionaMultipli1: selezionaMultipli1.c
	gcc -std=c11 -Wall -o selezionaMultipli1 selezionaMultipli1.c

selezionaMultipli2: selezionaMultipli2.c
	gcc -std=c11 -Wall -o selezionaMultipli2 selezionaMultipli2.c

